# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'prueba5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for prueba5
   pod 'Alamofire', '~> 5.2'
end
